<script setup lang="ts">
import type { Medicine, MedicineAttachment, MedicineAttachmentType } from "./medicine";
import { attachmentSections, formatDate, formatSize, statusLabel } from "./medicine";
const props = defineProps<{ medicine: Medicine; initialAttachments: MedicineAttachment[] }>();
const { apiFetch } = useApi(); const attachments = ref([...props.initialAttachments]); const uploading = ref<MedicineAttachmentType | null>(null);
async function upload(type: MedicineAttachmentType, file: File) {
  if (!file.type.startsWith("image/")) return ElMessage.error("请上传图片附件"); if (file.size > 20*1024*1024) return ElMessage.error("药品图片不能超过 20MB");
  uploading.value = type;
  try { const body = new FormData(); body.append("file", file); body.append("attachmentType", type); const result = await apiFetch<{ item: MedicineAttachment }>(`/api/medicines/${props.medicine.id}/attachments`, { method: "POST", body }); attachments.value.unshift(result.item); ElMessage.success("上传成功"); }
  catch (error) { ElMessage.error(error instanceof Error ? error.message : "上传失败"); } finally { uploading.value = null; }
}
async function remove(item: MedicineAttachment) {
  try { await ElMessageBox.confirm(`确定删除附件「${item.originalName}」？`, "删除附件", { type: "warning" }); await apiFetch(`/api/attachments/${item.id}`, { method: "DELETE" }); attachments.value = attachments.value.filter(entry => entry.id !== item.id); ElMessage.success("已删除"); }
  catch (error) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "删除失败"); }
}
</script>
<template><div class="page"><header><div><NuxtLink to="/medicines">← 返回药品列表</NuxtLink><h1>{{ medicine.name }}</h1><p>{{ medicine.category }}{{ medicine.tags ? ` · ${medicine.tags}` : '' }}</p></div><ElTag size="large">{{ statusLabel[medicine.status] }}</ElTag></header>
<ElCard shadow="never"><template #header><b>药品明细</b></template><div class="grid"><span>剩余量<b>{{ medicine.quantityRemaining ?? '-' }}{{ medicine.unit }} / {{ medicine.quantityTotal ?? '-' }}{{ medicine.unit }}</b></span><span>低库存阈值<b>{{ medicine.lowStockThreshold ?? '未设置' }}{{ medicine.lowStockThreshold !== null ? medicine.unit : '' }}</b></span><span>开封时间<b>{{ formatDate(medicine.openedAt) }}</b></span><span>过期日期<b>{{ formatDate(medicine.expiresAt) }}</b></span><span>过期提醒<b>提前 {{ medicine.expirationReminderDays }} 天</b></span><span>存放位置<b>{{ medicine.locationText || '未填写' }}</b></span><span>备注<b>{{ medicine.notes || '无' }}</b></span></div><ElDivider/><small>药品内容（文字）</small><p class="content">{{ medicine.contentText || '未填写，可上传内容照片。' }}</p></ElCard>
<div class="sections"><ElCard v-for="section in attachmentSections" :key="section.type" shadow="never"><template #header><div><b>{{ section.title }}</b><small>{{ section.description }} · {{ attachments.filter(a=>a.attachmentType===section.type).length }} 张</small></div></template><FileUpload accept="image/*" :limit-bytes="20*1024*1024" :disabled="!!uploading" @select="upload(section.type,$event)" @error="ElMessage.error($event)"><div class="upload">{{ uploading === section.type ? '上传中…' : '点击或拖拽图片上传（最大 20MB）' }}</div></FileUpload><div class="photos"><div v-for="file in attachments.filter(a=>a.attachmentType===section.type)" :key="file.id"><ElImage :src="file.url" :alt="file.originalName" fit="cover" :preview-src-list="[file.url]" preview-teleported/><span :title="file.originalName">{{ file.originalName }}<small>{{ formatSize(file.size) }}</small></span><ElButton text type="danger" aria-label="删除附件" @click="remove(file)">删除</ElButton></div></div></ElCard></div>
<ElCard shadow="never"><template #header><b>附件记录</b></template><ElEmpty v-if="!attachments.length" description="暂无附件"/><div v-else class="records"><div v-for="file in attachments" :key="file.id"><a :href="file.url" target="_blank" rel="noopener">{{ file.sourceLabel }} · {{ file.originalName }}</a><small>{{ new Date(file.createdAt).toLocaleDateString('zh-CN') }}</small><ElButton text type="danger" @click="remove(file)">删除</ElButton></div></div></ElCard></div></template>
<style scoped>.page{display:grid;gap:20px}header{display:flex;justify-content:space-between;align-items:end}h1{margin:8px 0 3px}p{margin:0;color:#64748b}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.grid span,.photos span{display:grid;color:#94a3b8;font-size:12px;gap:4px}.grid b{color:#334155;font-size:14px}.content{white-space:pre-wrap;margin-top:5px}.sections{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.sections :deep(.el-card__header)>div{display:grid;gap:5px}.sections small{color:#94a3b8}.upload{padding:15px;color:#64748b}.photos{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:12px}.photos>div{min-width:0}.photos :deep(.el-image){width:100%;height:120px;border-radius:8px}.photos span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.records>div{display:flex;align-items:center;gap:10px;padding:8px;border-bottom:1px solid #eee}.records a{flex:1;color:#2563eb}@media(max-width:800px){.grid,.sections{grid-template-columns:1fr 1fr}}@media(max-width:500px){.grid,.sections{grid-template-columns:1fr}}</style>
