<script setup lang="ts">
export type ManagedFile = { id: string; filename: string; originalName: string; mimetype: string; size: number; url: string; createdAt: string; licenseStoreAccountId?: string | null; sourceLabel?: string | null };
defineProps<{ files: ManagedFile[]; showSource?: boolean }>(); const emit = defineEmits<{ delete: [file: ManagedFile] }>();
const preview = ref<ManagedFile | null>(null); const copied = ref<string | null>(null);
const size = (bytes:number) => bytes >= 1024*1024 ? `${(bytes/1024/1024).toFixed(1)} MB` : `${(bytes/1024).toFixed(1)} KB`;
async function copy(file:ManagedFile) { try { await navigator.clipboard.writeText(file.url); copied.value=file.id; setTimeout(()=>copied.value=null,1500); } catch { ElMessage.error("复制失败"); } }
function icon(file:ManagedFile) { if(file.mimetype.startsWith("video/")) return "🎬"; if(file.mimetype.startsWith("audio/")) return "🎵"; if(file.mimetype.includes("pdf")) return "📄"; return "📎"; }
</script>
<template><ElEmpty v-if="!files.length" description="还没有文件"/><div v-else class="gallery"><ElCard v-for="file in files" :key="file.id" shadow="hover" body-class="body"><button v-if="file.mimetype.startsWith('image/')" class="thumb" aria-label="预览图片" @click="preview=file"><img :src="file.url" :alt="file.originalName" loading="lazy"></button><div v-else class="icon">{{ icon(file) }}</div><b :title="file.originalName">{{ file.originalName }}</b><small>{{ size(file.size) }} · {{ new Date(file.createdAt).toLocaleDateString('zh-CN') }}</small><small v-if="showSource && file.sourceLabel" class="source">📋 {{ file.sourceLabel }}</small><div class="buttons"><ElButton size="small" @click="copy(file)">{{ copied===file.id?'已复制':'复制' }}</ElButton><a :href="file.url" target="_blank" rel="noopener" :download="file.originalName"><ElButton size="small">下载</ElButton></a><ElButton v-if="!file.licenseStoreAccountId" size="small" type="danger" plain @click="emit('delete',file)">删除</ElButton><ElTag v-else>店铺管理</ElTag></div></ElCard></div><ElDialog :model-value="!!preview" :title="preview?.originalName" width="min(1000px, 94vw)" destroy-on-close @close="preview=null"><img v-if="preview" class="large" :src="preview.url" :alt="preview.originalName"></ElDialog></template>
<style scoped>.gallery{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.gallery :deep(.body){display:grid;gap:8px;min-width:0}.thumb,.icon{height:150px;width:100%;border:0;background:#f8fafc;padding:0}.thumb{cursor:zoom-in}.thumb img,.large{width:100%;height:100%;object-fit:contain}.icon{display:grid;place-items:center;font-size:45px}.gallery b,.gallery small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.gallery small{color:#94a3b8}.source{color:#3b82f6!important}.buttons{display:flex;gap:4px;flex-wrap:wrap}.large{max-height:72vh}@media(max-width:1100px){.gallery{grid-template-columns:repeat(4,1fr)}}@media(max-width:800px){.gallery{grid-template-columns:repeat(2,1fr)}}@media(max-width:400px){.gallery{grid-template-columns:1fr}}</style>
