<script setup lang="ts">
type Settings={appName:string;timezone:string;emailNotificationsEnabled:boolean;notificationEmail:string;smtpHost:string;smtpPort:number;smtpUser:string;smtpFromEmail:string;smtpFromName:string;smtpPasswordConfigured:boolean;reminderEmailEnabled:boolean;reminderEmailInterval:number;notifyStartHour:number;notifyEndHour:number};
type Log={id:string;task:string;startedAt:string;success:boolean;summary:string|null};
const defaults:Settings={appName:"提醒助手",timezone:"Asia/Shanghai",emailNotificationsEnabled:false,notificationEmail:"",smtpHost:"",smtpPort:587,smtpUser:"",smtpFromEmail:"",smtpFromName:"",smtpPasswordConfigured:false,reminderEmailEnabled:true,reminderEmailInterval:1800,notifyStartHour:9,notifyEndHour:22};
const {apiFetch}=useApi();const form=reactive({...defaults,smtpPass:"",clearSmtpPass:false});const logs=ref<Log[]>([]);const loading=ref(true);const saving=ref(false);const testing=ref(false);const testEmail=ref("");const message=ref("");
async function load(){loading.value=true;try{const data=await apiFetch<{item:Settings;taskLogs?:Log[]}>("/api/settings");Object.assign(form,data.item,{smtpPass:"",clearSmtpPass:false});testEmail.value=data.item.notificationEmail||"";logs.value=data.taskLogs||[]}catch(e){message.value=e instanceof Error?e.message:"加载配置失败"}finally{loading.value=false}}
onMounted(load);
async function save(){saving.value=true;try{const data=await apiFetch<{item:Partial<Settings>}>("/api/settings",{method:"PUT",body:{appName:form.appName,timezone:form.timezone,emailNotificationsEnabled:form.emailNotificationsEnabled,notificationEmail:form.notificationEmail.trim()||null,smtpHost:form.smtpHost,smtpPort:form.smtpPort,smtpUser:form.smtpUser,smtpPass:form.smtpPass,clearSmtpPass:form.clearSmtpPass,smtpFromEmail:form.smtpFromEmail,smtpFromName:form.smtpFromName,reminderEmailEnabled:form.reminderEmailEnabled,reminderEmailInterval:form.reminderEmailInterval,notifyStartHour:form.notifyStartHour,notifyEndHour:form.notifyEndHour}});Object.assign(form,data.item);form.smtpPass="";form.clearSmtpPass=false;message.value="配置已保存"}catch(e){message.value=e instanceof Error?e.message:"保存配置失败"}finally{saving.value=false}}
async function sendTest(){testing.value=true;try{const data=await apiFetch<{sentTo?:string}>("/api/settings/test-email",{method:"POST",body:{email:testEmail.value.trim()||null}});message.value=`测试邮件已发送到 ${data.sentTo||testEmail.value}` }catch(e){message.value=e instanceof Error?e.message:"测试邮件发送失败"}finally{testing.value=false}}
watch(()=>form.smtpPass,(v)=>{if(v)form.clearSmtpPass=false});watch(()=>form.clearSmtpPass,(v)=>{if(v)form.smtpPass=""});
</script>
<template><el-card v-loading="loading" shadow="never"><template #header><h2>应用与邮件设置</h2></template><el-form label-position="top" @submit.prevent="save"><div class="grid"><el-form-item label="系统名称"><el-input v-model="form.appName" /></el-form-item><el-form-item label="时区"><el-input v-model="form.timezone" /></el-form-item></div><el-divider content-position="left">邮件提醒</el-divider><el-switch v-model="form.emailNotificationsEnabled" active-text="启用邮箱提醒"/><div class="grid top"><el-form-item label="提醒接收邮箱"><el-input v-model="form.notificationEmail" type="email" /></el-form-item><el-form-item label="测试收件邮箱"><el-input v-model="testEmail" type="email" placeholder="留空使用提醒接收邮箱"><template #append><el-button :loading="testing" @click="sendTest">发送测试邮件</el-button></template></el-input></el-form-item></div><el-divider content-position="left">SMTP（密码不会回显，留空保持不变）</el-divider><div class="grid"><el-form-item label="SMTP Host"><el-input v-model="form.smtpHost" /></el-form-item><el-form-item label="SMTP Port"><el-input-number v-model="form.smtpPort" :min="1" :max="65535" /></el-form-item><el-form-item label="SMTP User"><el-input v-model="form.smtpUser" /></el-form-item><el-form-item label="SMTP Password"><el-input v-model="form.smtpPass" type="password" autocomplete="new-password" :placeholder="form.smtpPasswordConfigured?'已配置；留空保持不变':'输入 SMTP 密码'"/><el-checkbox v-model="form.clearSmtpPass">清空已保存密码</el-checkbox></el-form-item><el-form-item label="发件邮箱"><el-input v-model="form.smtpFromEmail" type="email" /></el-form-item><el-form-item label="发件人名称"><el-input v-model="form.smtpFromName" /></el-form-item></div><el-divider content-position="left">通知与定时任务</el-divider><div class="grid"><el-form-item label="通知开始小时"><el-input-number v-model="form.notifyStartHour" :min="0" :max="23" /></el-form-item><el-form-item label="通知结束小时"><el-input-number v-model="form.notifyEndHour" :min="0" :max="23" /></el-form-item><el-form-item label="到期提醒任务"><el-switch v-model="form.reminderEmailEnabled" active-text="启用" /></el-form-item><el-form-item label="发送间隔（秒）"><el-input-number v-model="form.reminderEmailInterval" :min="60" :max="86400" /></el-form-item></div><el-collapse v-if="logs.length"><el-collapse-item title="最近任务执行记录"><div v-for="log in logs.slice(0,30)" :key="log.id"><el-tag :type="log.success?'success':'danger'" size="small">{{log.success?'成功':'失败'}}</el-tag> {{log.summary||log.task}} · {{new Date(log.startedAt).toLocaleString('zh-CN')}}</div></el-collapse-item></el-collapse><div class="actions"><el-text type="info">{{message}}</el-text><el-button native-type="button" type="primary" :loading="saving" @click="save">保存配置</el-button></div></el-form></el-card></template>
<style scoped>h2{margin:0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px}.top{margin-top:16px}.actions{display:flex;justify-content:space-between;align-items:center;margin-top:18px}@media(max-width:600px){.grid{grid-template-columns:1fr}.actions{align-items:stretch;flex-direction:column}}</style>
