<script setup lang="ts">
import {ElMessageBox} from "element-plus";
type Bot={enabled:boolean;chatId:string;tokenConfigured:boolean;botName:string;botUsername:string;lastTestAt:string|null;lastTestStatus:string|null};type Binding={id:string;chatId:string;username:string|null;firstName:string|null;boundAt:string;lastActiveAt:string|null};
const {apiFetch}=useApi();const bot=reactive<Bot>({enabled:false,chatId:"",tokenConfigured:false,botName:"",botUsername:"",lastTestAt:null,lastTestStatus:null});const token=ref("");const clearToken=ref(false);const bindings=ref<Binding[]>([]);const bindCode=ref<{code:string;expiresAt:string;instructions:string}|null>(null);const loading=ref(true);const saving=ref(false);const testing=ref(false);const generating=ref(false);const message=ref("");
function apply(item:Partial<Bot>){Object.assign(bot,item)}
async function load(){loading.value=true;try{const [settings,bound]=await Promise.all([apiFetch<{item:Bot}>("/api/settings/bot"),apiFetch<{items:Binding[]}>("/api/settings/bot/bindings")]);apply(settings.item);bindings.value=bound.items}catch(e){message.value=e instanceof Error?e.message:"加载 Bot 配置失败"}finally{loading.value=false}}
onMounted(load);watch(token,v=>{if(v)clearToken.value=false});watch(clearToken,v=>{if(v)token.value=""});
async function save(){saving.value=true;try{const data=await apiFetch<{item:Bot}>("/api/settings/bot",{method:"PUT",body:{enabled:bot.enabled,chatId:bot.chatId,token:token.value,clearToken:clearToken.value}});apply(data.item);token.value="";clearToken.value=false;message.value="Bot 配置已保存"}catch(e){message.value=e instanceof Error?e.message:"保存失败"}finally{saving.value=false}}
async function test(){testing.value=true;try{const data=await apiFetch<{item?:Bot}>("/api/settings/bot",{method:"POST",body:{}});if(data.item)apply(data.item);message.value="测试通知已发送"}catch(e){message.value=e instanceof Error?e.message:"测试通知发送失败"}finally{testing.value=false}}
async function createCode(){generating.value=true;bindCode.value=null;try{const data=await apiFetch<{code:string;expiresAt:string;instructions:string}>("/api/settings/bot/bindings",{method:"POST",body:{action:"create-code"}});bindCode.value=data}catch(e){message.value=e instanceof Error?e.message:"生成失败"}finally{generating.value=false}}
async function unbind(item:Binding){try{await ElMessageBox.confirm(`确定解绑 Chat ID ${item.chatId}？`,"解绑 Telegram",{type:"warning"})}catch{return}try{await apiFetch("/api/settings/bot/bindings",{method:"POST",body:{action:"unbind",chatId:item.chatId}});bindings.value=bindings.value.filter(x=>x.id!==item.id);message.value="已解绑"}catch(e){message.value=e instanceof Error?e.message:"解绑失败"}}
async function copyCode(){if(bindCode.value){await navigator.clipboard.writeText(bindCode.value.code);message.value="绑定码已复制"}}
function time(value:string|null){return value?new Date(value).toLocaleString("zh-CN"):"暂无"}
</script>
<template><div v-loading="loading" class="bot-page"><el-card shadow="never"><template #header><div class="title"><div><el-text type="info">Telegram Bot</el-text><h2>Bot 通知管理</h2><p>Token 不会回显；留空保存会保持现有 Token。</p></div><el-tag :type="bot.enabled?'success':'info'">{{bot.enabled?'通知已启用':'通知未启用'}}</el-tag></div></template><div class="status"><div><el-text type="info">Token 状态</el-text><p>{{bot.tokenConfigured?'已保存':'未配置'}}</p></div><div><el-text type="info">Bot</el-text><p>{{bot.botUsername?`@${bot.botUsername}`:bot.botName||'待识别'}}</p></div><div><el-text type="info">最近测试</el-text><p>{{time(bot.lastTestAt)}}</p><el-text size="small">{{bot.lastTestStatus||''}}</el-text></div></div><el-form label-position="top" class="form"><el-switch v-model="bot.enabled" active-text="启用 Telegram Bot 通知"/><div class="grid"><el-form-item label="Bot Token"><el-input v-model="token" type="password" autocomplete="new-password" :placeholder="bot.tokenConfigured?'已配置；留空保持不变':'输入 Telegram Bot Token'"/><el-checkbox v-model="clearToken">清空已保存 Token</el-checkbox></el-form-item><el-form-item label="默认 Chat ID（备用）"><el-input v-model="bot.chatId" /></el-form-item></div></el-form><div class="actions"><el-text type="info">{{message}}</el-text><div><el-button :loading="testing" :disabled="saving" @click="test">发送测试通知</el-button><el-button type="primary" :loading="saving" :disabled="testing" @click="save">保存 Bot 配置</el-button></div></div></el-card>
<el-card shadow="never"><template #header><div class="title"><div><h2>绑定管理</h2><p>生成绑定码后，在 Telegram 中向 Bot 发送绑定命令。</p></div><el-button type="primary" :disabled="!bot.tokenConfigured" :loading="generating" @click="createCode">生成绑定码</el-button></div></template><el-alert v-if="bindCode" type="success" :closable="false"><template #title>绑定码有效期至 {{time(bindCode.expiresAt)}}</template><el-button class="code" @click="copyCode">{{bindCode.code}}</el-button><code>/bind {{bindCode.code}}</code></el-alert><el-empty v-if="!bindings.length" description="暂无绑定"/><el-table v-else :data="bindings"><el-table-column label="账号"><template #default="{row}">{{row.firstName||'未命名'}}<span v-if="row.username"> (@{{row.username}})</span></template></el-table-column><el-table-column prop="chatId" label="Chat ID"/><el-table-column label="绑定时间"><template #default="{row}">{{time(row.boundAt)}}</template></el-table-column><el-table-column width="100"><template #default="{row}"><el-button type="danger" link @click="unbind(row as Binding)">解绑</el-button></template></el-table-column></el-table></el-card></div></template>
<style scoped>.bot-page{display:grid;gap:24px}.title,.actions{display:flex;justify-content:space-between;gap:16px;align-items:center}h2,p{margin:4px 0}.status{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding-bottom:18px}.form{padding:16px;background:var(--el-fill-color-lighter);border-radius:8px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-top:16px}.code{margin:10px}.el-alert code{display:block;margin:8px;padding:8px;background:white}@media(max-width:600px){.title,.actions{align-items:stretch;flex-direction:column}.status,.grid{grid-template-columns:1fr}}</style>
