<script setup lang="ts">
type R2Response={endpoint:string;accessKey?:string;secretKey?:string;accessKeyConfigured?:boolean;secretKeyConfigured?:boolean;bucket:string;publicUrl:string;cacheControl:string};
const {apiFetch}=useApi(); const form=reactive({endpoint:"",accessKey:"",secretKey:"",bucket:"",publicUrl:"",cacheControl:"public, max-age=86400"}); const configured=reactive({accessKey:false,secretKey:false}); const loading=ref(true);const saving=ref(false);const testing=ref(false);const message=ref("");
// Kept outside reactive/template state solely for compatibility with the legacy API. It is never rendered or logged.
let preservedAccessKey=""; let preservedSecretKey="";
async function load(){loading.value=true;try{const data=await apiFetch<R2Response>("/api/settings/r2");form.endpoint=data.endpoint||"";form.bucket=data.bucket||"";form.publicUrl=data.publicUrl||"";form.cacheControl=data.cacheControl||"public, max-age=86400";preservedAccessKey=data.accessKey||"";preservedSecretKey=data.secretKey||"";configured.accessKey=Boolean(data.accessKeyConfigured||preservedAccessKey);configured.secretKey=Boolean(data.secretKeyConfigured||preservedSecretKey);form.accessKey="";form.secretKey=""}catch(e){message.value=e instanceof Error?e.message:"加载 R2 配置失败"}finally{loading.value=false}}
onMounted(load);
function credentials(){return{accessKey:form.accessKey.trim()||preservedAccessKey,secretKey:form.secretKey.trim()||preservedSecretKey}}
async function save(){saving.value=true;try{const creds=credentials();await apiFetch("/api/settings/r2",{method:"PUT",body:{endpoint:form.endpoint,...creds,bucket:form.bucket,publicUrl:form.publicUrl,cacheControl:form.cacheControl}});if(form.accessKey.trim())preservedAccessKey=form.accessKey.trim();if(form.secretKey.trim())preservedSecretKey=form.secretKey.trim();configured.accessKey=Boolean(preservedAccessKey);configured.secretKey=Boolean(preservedSecretKey);form.accessKey="";form.secretKey="";message.value="R2 配置已保存"}catch(e){message.value=e instanceof Error?e.message:"保存失败"}finally{saving.value=false}}
async function test(){testing.value=true;try{const data=await apiFetch<{success:boolean;message:string}>("/api/settings/r2",{method:"POST",body:{endpoint:form.endpoint,...credentials(),bucket:form.bucket}});message.value=data.message|| (data.success?"连接成功":"连接失败")}catch(e){message.value=e instanceof Error?e.message:"测试失败"}finally{testing.value=false}}
</script>
<template><el-card v-loading="loading" shadow="never"><template #header><div><h2>图床存储配置（R2）</h2><el-text type="info">凭据不会回显；留空保存或测试会沿用已配置值。</el-text></div></template><el-form label-position="top" class="grid"><el-form-item label="Endpoint"><el-input v-model="form.endpoint" placeholder="https://…r2.cloudflarestorage.com" /></el-form-item><el-form-item label="Bucket"><el-input v-model="form.bucket" /></el-form-item><el-form-item label="Access Key ID"><el-input v-model="form.accessKey" autocomplete="off" :placeholder="configured.accessKey?'已配置；留空保持不变':'输入 Access Key'" /></el-form-item><el-form-item label="Secret Access Key"><el-input v-model="form.secretKey" type="password" autocomplete="new-password" :placeholder="configured.secretKey?'已配置；留空保持不变':'输入 Secret Key'" /></el-form-item><el-form-item label="公开访问域名"><el-input v-model="form.publicUrl" /></el-form-item><el-form-item label="Cache-Control"><el-input v-model="form.cacheControl" /></el-form-item></el-form><div class="actions"><el-button :loading="testing" @click="test">测试连接</el-button><el-button type="primary" :loading="saving" @click="save">保存 R2 配置</el-button><el-text type="info">{{message}}</el-text></div></el-card></template>
<style scoped>h2{margin:0 0 4px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px}.actions{display:flex;align-items:center;gap:10px}@media(max-width:600px){.grid{grid-template-columns:1fr}.actions{align-items:stretch;flex-direction:column}}</style>
