<script setup lang="ts">
import type { ManagedFile } from "@/app/components/images/ImageGallery.vue";
definePageMeta({ layout: "default", middleware: "auth" }); const { apiFetch }=useApi();
const tab=ref<"images"|"attachments">("images"); const files=ref<ManagedFile[]>([]); const total=ref(0); const page=ref(1); const totalPages=ref(1); const search=ref(""); const type=ref("all"); const loading=ref(false);
async function load(){ loading.value=true; try{const query=new URLSearchParams({page:String(page.value),pageSize:"20",search:search.value,type:type.value}); const path=tab.value==="images"?`/api/images?${query}`:`/api/attachments?${query}`; const data=await apiFetch<{items:ManagedFile[];total:number;totalPages:number}>(path);files.value=data.items;total.value=data.total;totalPages.value=data.totalPages||1;}catch(error){ElMessage.error(error instanceof Error?error.message:"文件加载失败");}finally{loading.value=false;} }
watch([tab,page,type],()=>{load();}); let timer:ReturnType<typeof setTimeout>|undefined; watch(search,()=>{page.value=1;clearTimeout(timer);timer=setTimeout(load,250);}); onBeforeUnmount(()=>clearTimeout(timer)); await load();
function uploaded(file:ManagedFile){files.value.unshift(file);total.value++;}
async function remove(file:ManagedFile){try{await ElMessageBox.confirm(`确定删除「${file.originalName}」？`,"删除文件",{type:"warning"});await apiFetch(`${tab.value==="images"?"/api/images":"/api/attachments"}/${file.id}`,{method:"DELETE"});files.value=files.value.filter(i=>i.id!==file.id);total.value--;ElMessage.success("已删除");}catch(error){if(error!=="cancel"&&error!=="close")ElMessage.error(error instanceof Error?error.message:"删除失败");}}
function switchTab(name:string|number){tab.value=String(name) as typeof tab.value;page.value=1;search.value="";type.value="all";}
</script>
<template><div class="page"><header><h1>文件管理</h1><p>共 {{ total }} 个文件 · 上传到 Cloudflare R2</p></header><ElTabs :model-value="tab" type="border-card" @tab-change="switchTab"><ElTabPane label="🖼️ 图床文件" name="images"/><ElTabPane label="📎 提醒/药品附件" name="attachments"/></ElTabs><ImageUploader v-if="tab==='images'" @uploaded="uploaded"/><div class="filters"><ElInput v-model="search" clearable placeholder="搜索文件名…"/><ElSegmented v-model="type" :options="[{label:'全部',value:'all'},{label:'图片',value:'image'},{label:'文件',value:'file'}]"/></div><div v-loading="loading"><ImageGallery :files="files" :show-source="tab==='attachments'" @delete="remove"/></div><ElPagination v-if="totalPages>1" v-model:current-page="page" layout="prev, pager, next" :page-count="totalPages"/></div></template>
<style scoped>.page{display:grid;gap:20px}h1,p{margin:0}header p{margin-top:5px;color:#64748b}.filters{display:grid;grid-template-columns:1fr auto;gap:14px}.el-pagination{justify-content:center}@media(max-width:600px){.filters{grid-template-columns:1fr}}</style>
