<script setup lang="ts">
const voices=[{label:"中文女声",options:[["zh-CN-XiaoxiaoNeural","晓晓 · 温柔自然"],["zh-CN-XiaoyiNeural","晓伊 · 甜美活泼"],["zh-CN-XiaochenNeural","晓辰 · 知性清晰"]]},{label:"中文男声",options:[["zh-CN-YunxiNeural","云希 · 清朗青年"],["zh-CN-YunyangNeural","云扬 · 专业播报"],["zh-CN-YunjianNeural","云健 · 稳重成熟"]]},{label:"英文/日韩",options:[["en-US-JennyNeural","Jenny · 美式女声"],["en-US-GuyNeural","Guy · 美式男声"],["ja-JP-NanamiNeural","Nanami · 日语女声"],["ko-KR-SunHiNeural","SunHi · 韩语女声"]]}];
const AUDIO_ACCEPT=".mp3,.wav,.m4a,.flac,.aac,.ogg,.webm,.amr,.3gp,audio/mpeg,audio/wav,audio/mp4,audio/flac,audio/aac,audio/ogg,audio/webm,audio/amr,audio/3gpp";
definePageMeta({ layout: "default", middleware: "auth" });
const {apiFetch}=useApi();
const mode=ref<"tts"|"stt"|"assistant">("tts");
const text=ref("欢迎使用在线语音转换工具，这里可以把文字转换成自然流畅的语音。");
const voice=ref("zh-CN-XiaoxiaoNeural"),speed=ref(1),pitch=ref(0),volume=ref(0),generating=ref(false),audioUrl=ref(""),audioMime=ref(""),downloadName=ref("speech.mp3");
const audioFile=ref<File|null>(null),transcription=ref(""),transcribing=ref(false),custom=ref(false),token=ref("");
const baseUrl=ref(""),apiKey=ref(""),model=ref(""),systemPrompt=ref("你是提醒事项语音助手。需要时使用工具，并简洁地用中文回复。"),assistantInput=ref(""),autoSend=ref(true),allowMutations=ref(false),sending=ref(false);
const messages=ref<Array<{role:"user"|"assistant";content:string}>>([]),toolCalls=ref<Array<{name:string;arguments:Record<string,unknown>;status:string;result:string}>>([]);
const recording=ref(false),acquiring=ref(false),recordedFile=ref<File|null>(null);let recorder:MediaRecorder|null=null;let stream:MediaStream|null=null;let disposed=false;let transcriptionController:AbortController|null=null;let transcriptionGeneration=0;
function recorderState(){return recorder?.state||"inactive";}
function revoke(){if(audioUrl.value){URL.revokeObjectURL(audioUrl.value);audioUrl.value="";}}onBeforeUnmount(()=>{disposed=true;transcriptionGeneration++;transcriptionController?.abort();transcriptionController=null;transcribing.value=false;revoke();if(recorder){recorder.ondataavailable=null;recorder.onstop=null;if(recorder.state!=="inactive")try{recorder.stop();}catch{/* already stopping */}}recorder=null;stream?.getTracks().forEach(track=>track.stop());stream=null;});
async function responseError(response:Response,fallback:string){try{const data=await response.json();return data.error||data.message||fallback;}catch{return fallback;}}
function filename(header:string|null,mime:string){const utf=header?.match(/filename\*=UTF-8''([^;]+)/i)?.[1];const plain=header?.match(/filename="?([^";]+)"?/i)?.[1];if(utf)try{return decodeURIComponent(utf);}catch{/* ignored */}if(plain)return plain;const ext=mime.includes("wav")?"wav":mime.includes("ogg")?"ogg":"mp3";return `speech-${Date.now()}.${ext}`;}
async function generate(){if(!text.value.trim())return ElMessage.error("请输入要转换的文本内容");generating.value=true;try{const response=await fetch("/api/voice/tts",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:text.value,voice:voice.value,speed:speed.value,pitch:pitch.value,volume:volume.value})});if(!response.ok)throw new Error(await responseError(response,"生成失败"));const blob=await response.blob();revoke();audioMime.value=response.headers.get("content-type")||blob.type||"audio/mpeg";downloadName.value=filename(response.headers.get("content-disposition"),audioMime.value);audioUrl.value=URL.createObjectURL(blob);ElMessage.success("语音生成成功，可以播放或下载");}catch(error){ElMessage.error(error instanceof Error?error.message:"生成失败");}finally{generating.value=false;}}
async function txt(file:File){if(!(/\.txt$/i.test(file.name)||file.type==="text/plain"))return ElMessage.error("请选择 txt 文本文件");if(file.size>500*1024)return ElMessage.error("文本文件不能超过 500KB");try{text.value=(await file.text()).slice(0,8000);}catch{ElMessage.error("读取文本文件失败");}}
function audio(file:File){audioFile.value=null;if(file.size>10*1024*1024){ElMessage.error("音频文件不能超过 10MB");return false;}if(!/\.(?:mp3|wav|m4a|flac|aac|ogg|webm|amr|3gp)$/i.test(file.name)&&!file.type.startsWith("audio/")){ElMessage.error("不支持的音频格式");return false;}audioFile.value=file;return true;}
async function transcribe(file=audioFile.value,forAssistant=false){if(!file)return ElMessage.error("请选择要转录的音频文件");transcriptionController?.abort();const controller=new AbortController();const generation=++transcriptionGeneration;transcriptionController=controller;transcribing.value=true;try{const body=new FormData();body.append("file",file);if(custom.value&&token.value.trim())body.append("token",token.value.trim());const result=await apiFetch<{text:string}>("/api/voice/transcriptions",{method:"POST",body,signal:controller.signal});if(disposed||generation!==transcriptionGeneration)return;transcription.value=result.text||"";if(forAssistant){assistantInput.value=transcription.value;if(autoSend.value&&assistantInput.value.trim())await sendAssistant();}if(generation===transcriptionGeneration)ElMessage.success("语音转文字完成");}catch(error){if(generation===transcriptionGeneration&&!controller.signal.aborted)ElMessage.error(error instanceof Error?error.message:"转录失败");}finally{if(generation===transcriptionGeneration){transcriptionController=null;transcribing.value=false;}}}
async function copy(){try{await navigator.clipboard.writeText(transcription.value);ElMessage.success("已复制转录文本");}catch{ElMessage.error("复制失败");}}
function toTts(value=transcription.value){text.value=value;mode.value="tts";ElMessage.info("已填入文字转语音输入框");}
async function startRecording(){if(acquiring.value||recording.value||recorder)return;if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined")return ElMessage.error("当前浏览器不支持录音");acquiring.value=true;let acquired:MediaStream|null=null;let activeRecorder:MediaRecorder|null=null;try{acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(disposed){acquired.getTracks().forEach(track=>track.stop());return;}activeRecorder=new MediaRecorder(acquired);const localChunks:Blob[]=[];stream=acquired;recorder=activeRecorder;activeRecorder.ondataavailable=event=>{if(!disposed&&event.data.size)localChunks.push(event.data);};activeRecorder.onstop=()=>{activeRecorder!.ondataavailable=null;activeRecorder!.onstop=null;const type=activeRecorder!.mimeType||"audio/webm";if(!disposed)recordedFile.value=new File(localChunks,`recording-${Date.now()}.webm`,{type});acquired!.getTracks().forEach(track=>track.stop());if(stream===acquired)stream=null;if(recorder===activeRecorder)recorder=null;recording.value=false;};activeRecorder.start();recording.value=true;}catch{if(activeRecorder){activeRecorder.ondataavailable=null;activeRecorder.onstop=null;if(activeRecorder.state!=="inactive")try{activeRecorder.stop();}catch{/* start failed */}}acquired?.getTracks().forEach(track=>track.stop());if(stream===acquired)stream=null;if(recorder===activeRecorder)recorder=null;recording.value=false;if(!disposed)ElMessage.error("无法访问麦克风，请检查浏览器权限");}finally{acquiring.value=false;}}
function stopRecording(){if(recorder?.state==="recording")try{recorder.stop();}catch{/* already stopping */}}
function assistantAudio(file:File){recordedFile.value=null;if(!audio(file))return;recordedFile.value=file;void transcribe(file,true);}
async function sendAssistant(){const content=assistantInput.value.trim();if(!content)return ElMessage.error("请输入或转录一条消息");if(!apiKey.value.trim())return ElMessage.error("请输入 AI API Key");if(allowMutations.value)try{await ElMessageBox.confirm("本次请求允许 AI 创建或修改提醒/待办。确认继续？","确认 AI 修改权限",{type:"warning",confirmButtonText:"确认并发送",cancelButtonText:"取消"});}catch{return;}messages.value.push({role:"user",content});assistantInput.value="";sending.value=true;try{const result=await apiFetch<{reply:string;toolCalls:Array<{name:string;arguments:Record<string,unknown>;status:string;result:string}>;partial?:boolean}>("/api/voice/assistant",{method:'POST',body:{baseUrl:baseUrl.value,apiKey:apiKey.value,model:model.value,systemPrompt:systemPrompt.value,messages:messages.value,allowMutations:allowMutations.value}});toolCalls.value.push(...(result.toolCalls||[]));messages.value.push({role:"assistant",content:result.reply||"（AI 未返回文字）"});if(result.partial)ElMessage.warning("部分操作已执行，请检查工具调用结果，勿直接重试");}catch(error){ElMessage.error(error instanceof Error?error.message:"AI 请求失败");}finally{sending.value=false;}}
function speakReply(content:string){toTts(content);void nextTick(generate);}
</script>
<template><div class="page"><ElCard shadow="never"><div class="hero"><div><small>VoiceCraft</small><h1>语音转换</h1><p>文字、语音转写与可调用提醒工具的 AI 助手。</p></div><ElSegmented v-model="mode" :options="[{label:'🎙️ 文字转语音',value:'tts'},{label:'🎧 语音转文字',value:'stt'},{label:'✨ AI 语音助手',value:'assistant'}]"/></div></ElCard>
<div v-if="mode==='tts'" class="columns"><ElCard shadow="never"><FileUpload accept=".txt,text/plain" :limit-bytes="500*1024" @select="txt" @error="ElMessage.error($event)"><div class="upload">📄 点击或拖拽 txt 文件（最大 500KB）</div></FileUpload><ElInput v-model="text" type="textarea" :rows="14" maxlength="8000" show-word-limit/></ElCard><ElCard shadow="never"><ElForm label-position="top"><ElFormItem label="语音选择"><ElSelect v-model="voice"><ElOptionGroup v-for="group in voices" :key="group.label" :label="group.label"><ElOption v-for="entry in group.options" :key="entry[0]" :label="entry[1]" :value="entry[0]"/></ElOptionGroup></ElSelect></ElFormItem><ElFormItem :label="`语速 ${speed.toFixed(1)}x`"><ElSlider v-model="speed" :min="0.5" :max="2" :step="0.1"/></ElFormItem><ElFormItem :label="`音调 ${pitch}Hz`"><ElSlider v-model="pitch" :min="-50" :max="50"/></ElFormItem><ElFormItem :label="`音量 ${volume}%`"><ElSlider v-model="volume" :min="-100" :max="100"/></ElFormItem><ElButton type="primary" :loading="generating" class="wide" @click="generate">{{generating?'生成中…':'开始生成语音'}}</ElButton><div v-if="audioUrl" class="result"><audio :src="audioUrl" controls/><span>{{audioMime}} · {{downloadName}}</span><a :href="audioUrl" :download="downloadName"><ElButton class="wide">下载 {{downloadName}}</ElButton></a></div></ElForm></ElCard></div>
<div v-else-if="mode==='stt'" class="columns"><ElCard shadow="never"><FileUpload :accept="AUDIO_ACCEPT" :limit-bytes="10*1024*1024" @select="audio" @error="ElMessage.error($event)"><div class="upload">🎧 点击或拖拽音频（最大 10MB）</div></FileUpload><ElAlert v-if="audioFile" :title="audioFile.name" type="info" :closable="false"/><div v-if="transcription" class="transcription"><div><b>转录结果</b><ElButton text @click="copy">复制</ElButton><ElButton text type="primary" @click="toTts()">转为语音</ElButton></div><ElInput v-model="transcription" type="textarea" :rows="10"/></div></ElCard><ElCard shadow="never"><ElSwitch v-model="custom" active-text="使用自定义硅基流动 Token" inactive-text="使用服务器默认 Token"/><ElInput v-if="custom" v-model="token" class="token" type="password" show-password placeholder="sk-…"/><ElAlert title="STT Token 仅随本次请求发送。" type="warning" :closable="false"/><ElButton type="primary" :loading="transcribing" class="wide" @click="transcribe()">开始语音转文字</ElButton></ElCard></div>
<div v-else class="assistant-grid"><ElCard shadow="never"><template #header><b>AI 配置</b></template><ElForm label-position="top"><ElFormItem label="Base URL"><ElInput v-model="baseUrl" placeholder="留空使用服务器 VOICE_ASSISTANT_BASE_URL"/></ElFormItem><ElFormItem label="API Key（不保存）"><ElInput v-model="apiKey" type="password" show-password autocomplete="off" placeholder="仅随本次请求发送"/></ElFormItem><ElFormItem label="Model"><ElInput v-model="model" placeholder="留空使用服务器 VOICE_ASSISTANT_MODEL"/></ElFormItem><ElFormItem label="System Prompt"><ElInput v-model="systemPrompt" type="textarea" :rows="4" maxlength="8000"/></ElFormItem><ElFormItem><ElSwitch v-model="allowMutations" active-text="允许本次对话修改提醒/待办"/></ElFormItem></ElForm><ElAlert title="默认仅开放读取工具；启用修改权限后，每次发送仍需确认。删除工具始终不会提供给 AI。AI Key 不会持久化。" type="warning" :closable="false"/></ElCard>
<ElCard shadow="never" class="chat"><template #header><div class="chat-head"><b>对话</b><ElSwitch v-model="autoSend" active-text="转录后自动发送"/></div></template><div class="messages"><ElEmpty v-if="!messages.length" description="录音、上传音频或直接输入消息"/><div v-for="(message,index) in messages" :key="index" :class="['bubble',message.role]"><b>{{message.role==='user'?'你':'AI'}}</b><p>{{message.content}}</p><ElButton v-if="message.role==='assistant'" size="small" text type="primary" @click="speakReply(message.content)">🔊 TTS 播放</ElButton></div></div><ElCollapse v-if="toolCalls.length"><ElCollapseItem title="MCP 工具调用过程"><div v-for="(call,index) in toolCalls" :key="index" class="tool"><ElTag :type="call.status==='success'?'success':'danger'">{{call.name}}</ElTag><code>{{JSON.stringify(call.arguments)}}</code><small>{{call.result}}</small></div></ElCollapseItem></ElCollapse><div class="composer"><ElInput v-model="assistantInput" type="textarea" :rows="3" placeholder="输入消息，或使用下方语音转录" @keydown.ctrl.enter="sendAssistant"/><ElButton type="primary" :loading="sending" @click="sendAssistant">发送给 AI</ElButton></div></ElCard>
<ElCard shadow="never"><template #header><b>语音输入</b></template><div class="record"><ElButton v-if="!recording" type="danger" :loading="acquiring" :disabled="acquiring||recorderState()!=='inactive'" @click="startRecording">🎙️ 开始录音</ElButton><ElButton v-else type="warning" :disabled="recorderState()!=='recording'" @click="stopRecording">⏹ 停止录音</ElButton><ElButton v-if="recordedFile" :loading="transcribing" @click="transcribe(recordedFile,true)">转录录音</ElButton></div><FileUpload :accept="AUDIO_ACCEPT" :limit-bytes="10*1024*1024" @select="assistantAudio" @error="ElMessage.error($event)"><div class="upload">上传现有音频并转录</div></FileUpload><ElInput v-if="custom" v-model="token" type="password" show-password placeholder="自定义 STT Token"/><ElSwitch v-model="custom" active-text="自定义 STT Token"/></ElCard></div></div></template>
<style scoped>.page{display:grid;gap:20px}.hero,.chat-head{display:flex;align-items:center;justify-content:space-between;gap:15px}h1,p{margin:4px 0}.hero small{color:#2563eb}.hero p{color:#64748b}.columns{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px}.assistant-grid{display:grid;grid-template-columns:300px minmax(0,1fr) 260px;gap:18px;align-items:start}.upload{text-align:center;padding:20px;color:#475569}.wide,a,a .el-button,audio{width:100%}.result,.transcription,.composer,.record,.tool{display:grid;gap:10px;margin-top:16px}.result span,.tool small{font-size:12px;color:#64748b;overflow-wrap:anywhere}.token{margin:16px 0}.messages{display:grid;gap:12px;max-height:480px;overflow:auto}.bubble{padding:12px;border-radius:12px;background:#f1f5f9}.bubble.user{margin-left:15%;background:#dbeafe}.bubble.assistant{margin-right:15%}.bubble p{white-space:pre-wrap}.tool code{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:1000px){.assistant-grid{grid-template-columns:1fr}.chat{grid-row:auto}}@media(max-width:800px){.hero{align-items:flex-start;flex-direction:column}.columns{grid-template-columns:1fr}}</style>
