<script setup lang="ts">
const voices=[{label:"中文女声",options:[["zh-CN-XiaoxiaoNeural","晓晓 · 温柔自然"],["zh-CN-XiaoyiNeural","晓伊 · 甜美活泼"],["zh-CN-XiaochenNeural","晓辰 · 知性清晰"]]},{label:"中文男声",options:[["zh-CN-YunxiNeural","云希 · 清朗青年"],["zh-CN-YunyangNeural","云扬 · 专业播报"],["zh-CN-YunjianNeural","云健 · 稳重成熟"]]},{label:"英文/日韩",options:[["en-US-JennyNeural","Jenny · 美式女声"],["en-US-GuyNeural","Guy · 美式男声"],["ja-JP-NanamiNeural","Nanami · 日语女声"],["ko-KR-SunHiNeural","SunHi · 韩语女声"]]}];
const AUDIO_ACCEPT=".mp3,.wav,.m4a,.flac,.aac,.ogg,.webm,.amr,.3gp,audio/mpeg,audio/wav,audio/mp4,audio/flac,audio/aac,audio/ogg,audio/webm,audio/amr,audio/3gpp";
definePageMeta({ layout: "default", middleware: "auth" }); const {apiFetch}=useApi();
const mode=ref<"tts"|"stt">("tts");const text=ref("欢迎使用在线语音转换工具，这里可以把文字转换成自然流畅的语音。");const voice=ref("zh-CN-XiaoxiaoNeural");const speed=ref(1);const pitch=ref(0);const volume=ref(0);const generating=ref(false);const audioUrl=ref("");const audioMime=ref("");const downloadName=ref("speech.mp3");const audioFile=ref<File|null>(null);const transcription=ref("");const transcribing=ref(false);const custom=ref(false);const token=ref("");
function revoke(){if(audioUrl.value){URL.revokeObjectURL(audioUrl.value);audioUrl.value="";}} onBeforeUnmount(revoke);
async function responseError(response:Response,fallback:string){try{const data=await response.json();return data.error||data.message||fallback;}catch{return fallback;}}
function filename(header:string|null,mime:string){const utf=header?.match(/filename\*=UTF-8''([^;]+)/i)?.[1];const plain=header?.match(/filename="?([^";]+)"?/i)?.[1];if(utf)try{return decodeURIComponent(utf);}catch{/* ignored */}if(plain)return plain;const ext=mime.includes("wav")?"wav":mime.includes("ogg")?"ogg":"mp3";return `speech-${Date.now()}.${ext}`;}
async function generate(){if(!text.value.trim())return ElMessage.error("请输入要转换的文本内容");generating.value=true;try{const response=await fetch("/api/voice/tts",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:text.value,voice:voice.value,speed:speed.value,pitch:pitch.value,volume:volume.value})});if(!response.ok)throw new Error(await responseError(response,"生成失败"));const blob=await response.blob();revoke();audioMime.value=response.headers.get("content-type")||blob.type||"audio/mpeg";downloadName.value=filename(response.headers.get("content-disposition"),audioMime.value);audioUrl.value=URL.createObjectURL(blob);ElMessage.success("语音生成成功，可以播放或下载");}catch(error){ElMessage.error(error instanceof Error?error.message:"生成失败");}finally{generating.value=false;}}
async function txt(file:File){if(!(/\.txt$/i.test(file.name)||file.type==="text/plain"))return ElMessage.error("请选择 txt 文本文件");if(file.size>500*1024)return ElMessage.error("文本文件不能超过 500KB");try{text.value=(await file.text()).slice(0,8000);ElMessage.success(`已读取 ${file.name}`);}catch{ElMessage.error("文本文件读取失败");}}
function audio(file:File){if(file.size>10*1024*1024)return ElMessage.error("音频文件不能超过 10MB");if(!/\.(?:mp3|wav|m4a|flac|aac|ogg|webm|amr|3gp)$/i.test(file.name)&&!file.type.startsWith("audio/"))return ElMessage.error("不支持的音频格式");audioFile.value=file;}
async function transcribe(){if(!audioFile.value)return ElMessage.error("请选择要转录的音频文件");transcribing.value=true;try{const body=new FormData();body.append("file",audioFile.value);if(custom.value&&token.value.trim())body.append("token",token.value.trim());const result=await apiFetch<{text:string}>("/api/voice/transcriptions",{method:"POST",body});transcription.value=result.text||"";ElMessage.success("语音转文字完成");}catch(error){ElMessage.error(error instanceof Error?error.message:"转录失败");}finally{transcribing.value=false;}}
async function copy(){try{await navigator.clipboard.writeText(transcription.value);ElMessage.success("已复制转录文本");}catch{ElMessage.error("复制失败");}}
function toTts(){text.value=transcription.value;mode.value="tts";ElMessage.info("已填入文字转语音输入框");}
</script>
<template><div class="page"><ElCard shadow="never"><div class="hero"><div><small>VoiceCraft</small><h1>语音转换</h1><p>Microsoft Edge 在线 TTS 与 SenseVoice 语音转写。</p></div><ElSegmented v-model="mode" :options="[{label:'🎙️ 文字转语音',value:'tts'},{label:'🎧 语音转文字',value:'stt'}]"/></div></ElCard>
<div v-if="mode==='tts'" class="columns"><ElCard shadow="never"><FileUpload accept=".txt,text/plain" :limit-bytes="500*1024" @select="txt" @error="ElMessage.error($event)"><div class="upload">📄 点击或拖拽 txt 文件（最大 500KB）</div></FileUpload><ElInput v-model="text" type="textarea" :rows="14" maxlength="8000" show-word-limit placeholder="请输入要转换成语音的文字…"/></ElCard><ElCard shadow="never"><ElForm label-position="top"><ElFormItem label="语音选择"><ElSelect v-model="voice"><ElOptionGroup v-for="group in voices" :key="group.label" :label="group.label"><ElOption v-for="entry in group.options" :key="entry[0]" :label="entry[1]" :value="entry[0]"/></ElOptionGroup></ElSelect></ElFormItem><ElFormItem :label="`语速 ${speed.toFixed(1)}x`"><ElSlider v-model="speed" :min="0.5" :max="2" :step="0.1"/></ElFormItem><ElFormItem :label="`音调 ${pitch}Hz`"><ElSlider v-model="pitch" :min="-50" :max="50"/></ElFormItem><ElFormItem :label="`音量 ${volume}%`"><ElSlider v-model="volume" :min="-100" :max="100"/></ElFormItem><ElButton type="primary" :loading="generating" class="wide" @click="generate">{{generating?'生成中…':'开始生成语音'}}</ElButton><div v-if="audioUrl" class="result"><audio :src="audioUrl" controls/><span>{{ audioMime }} · {{ downloadName }}</span><a :href="audioUrl" :download="downloadName"><ElButton class="wide">下载 {{ downloadName }}</ElButton></a></div></ElForm></ElCard></div>
<div v-else class="columns"><ElCard shadow="never"><FileUpload :accept="AUDIO_ACCEPT" :limit-bytes="10*1024*1024" @select="audio" @error="ElMessage.error($event)"><div class="upload">🎧 点击或拖拽音频<br><small>mp3、wav、m4a、flac、aac、ogg、webm、amr、3gp，最大 10MB</small></div></FileUpload><ElAlert v-if="audioFile" :title="`${audioFile.name} · ${(audioFile.size/1024/1024).toFixed(2)} MB`" type="info" :closable="false"/><div v-if="transcription" class="transcription"><div><b>转录结果</b><ElButton text @click="copy">复制</ElButton><ElButton text type="primary" @click="toTts">转为语音</ElButton></div><ElInput v-model="transcription" type="textarea" :rows="10"/></div></ElCard><ElCard shadow="never"><ElSwitch v-model="custom" active-text="使用自定义硅基流动 Token" inactive-text="使用服务器默认 Token"/><ElInput v-if="custom" v-model="token" class="token" type="password" show-password placeholder="sk-…"/><ElAlert title="STT 使用 FunAudioLLM/SenseVoiceSmall；Token 仅随本次请求发送。" type="warning" :closable="false"/><ElButton type="primary" :loading="transcribing" class="wide" @click="transcribe">{{transcribing?'转录中…':'开始语音转文字'}}</ElButton></ElCard></div></div></template>
<style scoped>.page{display:grid;gap:20px}.hero{display:flex;align-items:center;justify-content:space-between;gap:15px}h1,p{margin:4px 0}.hero small{color:#2563eb}.hero p{color:#64748b}.columns{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px}.upload{text-align:center;padding:20px;color:#475569}.wide,a,a .el-button,audio{width:100%}.result,.transcription{display:grid;gap:10px;margin-top:16px}.result span{font-size:12px;color:#64748b}.token{margin:16px 0}.columns :deep(.el-alert){margin:16px 0}@media(max-width:800px){.hero{align-items:flex-start;flex-direction:column}.columns{grid-template-columns:1fr}}</style>
