<script setup lang="ts">
import { ElMessageBox } from "element-plus";
type Reminder = { id:string; title:string };
type Account = { id:string; shopName:string; phone:string; remoteCode:string; remotePassword:string; isOtherAccount:boolean; expiresAt:string; activationCode:string; reminderId:string|null; reminder:Reminder|null };
type Form = Omit<Account,"id"|"reminderId"|"reminder">;
const empty = (): Form => ({ shopName:"",phone:"",remoteCode:"",remotePassword:"",isOtherAccount:false,expiresAt:"",activationCode:"" });
const { apiFetch } = useApi(); const items=ref<Account[]>([]); const form=reactive<Form>(empty()); const editingId=ref(""); const search=ref(""); const loading=ref(false); const saving=ref(false); const deleting=ref(""); const qrId=ref(""); const message=ref("");
function localDate(value:string){ const d=new Date(value); if(Number.isNaN(d.getTime())) return ""; return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16); }
function reset(){ Object.assign(form,empty()); editingId.value=""; }
function edit(item:Account){ editingId.value=item.id; Object.assign(form,{shopName:item.shopName,phone:item.phone,remoteCode:item.remoteCode,remotePassword:item.remotePassword,isOtherAccount:item.isOtherAccount,expiresAt:localDate(item.expiresAt),activationCode:item.activationCode}); message.value=`正在编辑：${item.shopName}`; }
async function load(){ loading.value=true; try { const q=search.value.trim()?`?q=${encodeURIComponent(search.value.trim())}`:""; const data=await apiFetch<{items:Account[]}>(`/api/license/store-accounts${q}`); items.value=data.items; if(qrId.value&&!items.value.some(x=>x.id===qrId.value)) qrId.value=""; } catch(e){message.value=e instanceof Error?e.message:"加载失败"} finally{loading.value=false} }
onMounted(load);
async function save(){ saving.value=true; try { const body={...form,expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():""}; const wasEdit=Boolean(editingId.value); await apiFetch(editingId.value?`/api/license/store-accounts/${editingId.value}`:"/api/license/store-accounts",{method:editingId.value?"PUT":"POST",body}); reset(); await load(); message.value=wasEdit?"已保存店铺账号":"已新增店铺账号"; } catch(e){message.value=e instanceof Error?e.message:"保存失败"} finally{saving.value=false} }
async function remove(item:Account){try{await ElMessageBox.confirm(`确定删除店铺账号“${item.shopName}”吗？店铺关联提醒和收款码也会原子删除。`,"删除店铺账号",{type:"warning"})}catch{return} deleting.value=item.id;try{await apiFetch(`/api/license/store-accounts/${item.id}`,{method:"DELETE"});if(editingId.value===item.id)reset();await load();message.value="已删除店铺账号"}catch(e){message.value=e instanceof Error?e.message:"删除失败"}finally{deleting.value=""}}
function remaining(value:string){return Math.ceil((new Date(value).getTime()-Date.now())/86400000)}
</script>
<template><el-card shadow="never"><template #header><div class="heading"><div><el-text type="info">店铺账号维护</el-text><h2>激活码关联店铺</h2><p>新增、更新和删除会由服务端原子同步关联提醒。</p></div><el-form inline @submit.prevent="load"><el-input v-model="search" placeholder="搜索店铺/手机号/远程码/激活码" clearable/><el-button native-type="submit" :loading="loading">查询</el-button></el-form></div></template>
<el-form label-position="top" class="form" @submit.prevent="save"><el-form-item label="店铺名"><el-input v-model="form.shopName" /></el-form-item><el-form-item label="手机号"><el-input v-model="form.phone" /></el-form-item><el-form-item label="远程码"><el-input v-model="form.remoteCode" /></el-form-item><el-form-item label="远程密码"><el-input v-model="form.remotePassword" type="password" show-password /></el-form-item><el-form-item label="到期时间"><el-date-picker v-model="form.expiresAt" type="datetime" value-format="YYYY-MM-DDTHH:mm" placeholder="选择到期时间" /></el-form-item><el-form-item label="是否他人账号"><el-switch v-model="form.isOtherAccount" /></el-form-item><el-form-item label="对应激活码" class="activation"><el-input v-model="form.activationCode" type="textarea" :rows="3" maxlength="20000" show-word-limit /></el-form-item><div class="form-actions"><el-button native-type="submit" type="primary" :loading="saving">{{ editingId?"保存修改":"新增店铺账号" }}</el-button><el-button v-if="editingId" @click="reset">取消编辑</el-button><el-text type="info">{{ message }}</el-text></div></el-form>
<el-table v-loading="loading" :data="items" row-key="id" empty-text="暂无店铺账号记录"><el-table-column prop="shopName" label="店铺名" min-width="130"/><el-table-column prop="phone" label="手机号" min-width="130"/><el-table-column label="远程凭据" min-width="150"><template #default><span>••••••••</span></template></el-table-column><el-table-column label="到期时间" min-width="180"><template #default="{row}"><div>{{new Date(row.expiresAt).toLocaleString('zh-CN',{hour12:false})}}</div><el-tag :type="remaining(row.expiresAt)<0?'danger':remaining(row.expiresAt)<=7?'warning':'success'" size="small">{{remaining(row.expiresAt)<0?`已过期 ${Math.abs(remaining(row.expiresAt))} 天`:`剩余 ${remaining(row.expiresAt)} 天`}}</el-tag></template></el-table-column><el-table-column label="关联提醒" min-width="130"><template #default="{row}"><NuxtLink v-if="row.reminder" :to="`/reminders/${row.reminder.id}/edit`">{{row.reminder.title}}</NuxtLink><span v-else>未关联</span></template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{row}"><el-button size="small" @click="qrId=qrId===row.id?'':row.id">收款码</el-button><el-button size="small" @click="edit(row as Account)">编辑</el-button><el-button size="small" type="danger" :loading="deleting===row.id" @click="remove(row as Account)">删除</el-button></template></el-table-column><template #append><div v-if="qrId" class="qr-wrap"><PaymentQrManager :account-id="qrId" :shop-name="items.find(x=>x.id===qrId)?.shopName||''" /></div></template></el-table></el-card></template>
<style scoped>.heading{display:flex;justify-content:space-between;gap:20px;align-items:end}h2,p{margin:4px 0}.form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0 12px;padding:16px;background:var(--el-fill-color-lighter);border-radius:8px;margin-bottom:16px}.activation{grid-column:span 2}.form-actions{grid-column:1/-1;display:flex;align-items:center;gap:10px}.qr-wrap{padding:16px}@media(max-width:900px){.heading{align-items:stretch;flex-direction:column}.form{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.form{grid-template-columns:1fr}.activation{grid-column:auto}.form-actions{align-items:stretch;flex-direction:column}}</style>
