import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type ManifestEntry = { source: string; path: string; methods: string[] };

function handlerImport(source: string): string {
  if (!source.startsWith("app/") || !source.endsWith("/route.ts")) {
    throw new Error(`Unexpected route manifest source: ${source}`);
  }
  return `@/server/handlers/${source.slice("app/".length).replace(/\.ts$/, "")}`;
}

async function main() {
  const root = resolve(__dirname, "..");
  const fixturePath = resolve(root, "tests/fixtures/contracts/route-manifest.json");
  const outputPath = resolve(root, "server/http/route-registry.ts");
  const manifest = JSON.parse(await readFile(fixturePath, "utf8")) as ManifestEntry[];

  const imports = manifest.map((entry, index) =>
    `import * as route${index} from ${JSON.stringify(handlerImport(entry.source))};`,
  );
  const definitions = manifest.flatMap((entry, index) => entry.methods.map((method) => {
    const path = entry.path.replace(/\[([^\]]+)\]/g, ":$1");
    return `  { source: ${JSON.stringify(entry.source)}, path: ${JSON.stringify(path)}, method: ${JSON.stringify(method)} as const, handler: adaptRouteHandler(route${index}.${method}) },`;
  }));

  const output = `// Generated by scripts/generate-route-registry.ts. Do not add runtime discovery here.\n${imports.join("\n")}\n\nimport { compileRoute } from "./compile-route";\nimport type { RouteHandler } from "./types";\n\n// Every registered module is checked by the manifest and contract tests. This adapter is\n// the single boundary for route-specific parameter shapes such as { id } and { token }.\nfunction adaptRouteHandler(handler: unknown): RouteHandler {\n  return handler as RouteHandler;\n}\n\nexport const routeRegistry = [\n${definitions.join("\n")}\n].map(compileRoute);\n`;

  await writeFile(outputPath, output);
  console.log(`Generated ${manifest.length} paths / ${definitions.length} handlers`);
}

void main();
