<script setup lang="ts">
import {ElMessageBox} from "element-plus";
type Status={lastRenew:string|null;lastCheck?:string|null;lastResult:number|null;lastAction?:string|null;message?:string|null;expiry:string|null;updated:string|null;daysRemaining?:number;subject?:string;issuer?:string;serialNumber?:string;isExpired?:boolean};type Data={status:Status;acmeList:string;logs:string;certPath:string;renewScript:string};
const {apiFetch}=useApi();const data=ref<Data|null>(null);const loading=ref(true);const renewing=ref(false);const error=ref("");const result=ref<{success:boolean;skipped?:boolean;message:string}|null>(null);
async function load(){loading.value=true;try{data.value=await apiFetch<Data>("/api/ssl");error.value=""}catch(e){error.value=e instanceof Error?e.message:"获取 SSL 状态失败"}finally{loading.value=false}}
onMounted(load);
async function renew(){try{await ElMessageBox.confirm("确定检查 SSL 证书吗？未进入 30 天续期窗口会自动跳过。","检查并按需更新",{type:"warning"})}catch{return}renewing.value=true;result.value=null;try{const response=await apiFetch<{success:boolean;skipped?:boolean;message?:string;error?:string}>("/api/ssl",{method:"POST"});result.value={success:response.success,skipped:response.skipped,message:response.message||response.error||"检查完成"};if(response.success)await load()}catch(e){result.value={success:false,message:e instanceof Error?e.message:"更新失败"}}finally{renewing.value=false}}
function date(value?:string|null){return value?new Date(value).toLocaleString("zh-CN",{hour12:false}):"-"}const stateType=computed(()=>data.value?.status.isExpired?"danger":(data.value?.status.daysRemaining??999)<=30?"warning":"success");
</script>
<template><div class="ssl"><header><div><h1>SSL 证书管理</h1><p>管理和监控 SSL 证书状态</p></div><div><el-button :loading="loading" @click="load">刷新</el-button><el-button type="primary" :loading="renewing" @click="renew">检查并按需更新</el-button></div></header><el-alert v-if="error" :title="error" type="error" show-icon><el-button @click="load">重试</el-button></el-alert><el-alert v-if="result" :title="result.message" :type="result.skipped?'warning':result.success?'success':'error'" :closable="false" show-icon/>
<el-skeleton v-if="loading&&!data" :rows="8" animated/><template v-else-if="data"><div class="stats"><el-card shadow="never"><el-text type="info">证书状态</el-text><h3>{{data.status.isExpired?'已过期':'正常'}} <el-tag :type="stateType">{{data.status.isExpired?'需处理':'有效'}}</el-tag></h3></el-card><el-card shadow="never"><el-text type="info">剩余天数</el-text><h3>{{data.status.daysRemaining??'-'}}</h3></el-card><el-card shadow="never"><el-text type="info">到期时间</el-text><h3>{{date(data.status.expiry)}}</h3></el-card><el-card shadow="never"><el-text type="info">上次检查</el-text><h3>{{date(data.status.lastCheck||data.status.lastRenew)}}</h3></el-card></div><el-card shadow="never"><template #header><h2>证书详细信息</h2></template><el-descriptions :column="2" border><el-descriptions-item label="域名 (Subject)">{{data.status.subject||'-'}}</el-descriptions-item><el-descriptions-item label="颁发机构 (Issuer)">{{data.status.issuer||'-'}}</el-descriptions-item><el-descriptions-item label="序列号">{{data.status.serialNumber||'-'}}</el-descriptions-item><el-descriptions-item label="证书路径">{{data.certPath||'-'}}</el-descriptions-item><el-descriptions-item label="最近结果" :span="2">{{data.status.message||data.status.lastAction||'-'}}</el-descriptions-item></el-descriptions></el-card><el-card shadow="never"><template #header><h2>更新日志</h2></template><pre>{{data.logs||'暂无日志'}}</pre></el-card><el-card shadow="never"><template #header><h2>ACME 证书列表</h2></template><pre>{{data.acmeList||'无数据'}}</pre></el-card><el-alert title="系统每月 1 日和 15 日自动检查；剩余天数大于 30 天时跳过更新。" type="info" :closable="false"/></template></div></template>
<style scoped>.ssl{display:grid;gap:20px}header{display:flex;justify-content:space-between;align-items:center;gap:16px}h1,h2,p{margin:4px 0}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}pre{max-height:240px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;padding:14px;background:var(--el-fill-color-lighter);border-radius:6px}@media(max-width:900px){.stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){header{align-items:stretch;flex-direction:column}.stats{grid-template-columns:1fr}}</style>
