// Generated by scripts/generate-route-registry.ts. Do not add runtime discovery here.
import * as route0 from "@/server/handlers/.well-known/ai-plugin.json/route";
import * as route1 from "@/server/handlers/api/admin/member-invitations/[id]/route";
import * as route2 from "@/server/handlers/api/admin/members/[id]/revoke-access/route";
import * as route3 from "@/server/handlers/api/admin/members/[id]/route";
import * as route4 from "@/server/handlers/api/admin/members/route";
import * as route5 from "@/server/handlers/api/attachments/[id]/route";
import * as route6 from "@/server/handlers/api/attachments/route";
import * as route7 from "@/server/handlers/api/auth/logout/route";
import * as route8 from "@/server/handlers/api/auth/otp/login/route";
import * as route9 from "@/server/handlers/api/auth/otp/setup/route";
import * as route10 from "@/server/handlers/api/auth/otp/verify-setup/route";
import * as route11 from "@/server/handlers/api/auth/passkey/[id]/route";
import * as route12 from "@/server/handlers/api/auth/passkey/list/route";
import * as route13 from "@/server/handlers/api/auth/passkey/login/route";
import * as route14 from "@/server/handlers/api/auth/passkey/login/verify/route";
import * as route15 from "@/server/handlers/api/auth/passkey/register/route";
import * as route16 from "@/server/handlers/api/auth/passkey/register/verify/route";
import * as route17 from "@/server/handlers/api/auth/status/route";
import * as route18 from "@/server/handlers/api/auth/trusted/devices/route";
import * as route19 from "@/server/handlers/api/auth/trusted/restore/route";
import * as route20 from "@/server/handlers/api/images/[id]/route";
import * as route21 from "@/server/handlers/api/images/route";
import * as route22 from "@/server/handlers/api/invite/[token]/passkey/options/route";
import * as route23 from "@/server/handlers/api/invite/[token]/passkey/verify/route";
import * as route24 from "@/server/handlers/api/invite/[token]/totp/setup/route";
import * as route25 from "@/server/handlers/api/invite/[token]/totp/verify/route";
import * as route26 from "@/server/handlers/api/license/generate/route";
import * as route27 from "@/server/handlers/api/license/store-accounts/[id]/payment-qr/route";
import * as route28 from "@/server/handlers/api/license/store-accounts/[id]/route";
import * as route29 from "@/server/handlers/api/license/store-accounts/route";
import * as route30 from "@/server/handlers/api/mcp/route";
import * as route31 from "@/server/handlers/api/medicines/[id]/attachments/route";
import * as route32 from "@/server/handlers/api/medicines/[id]/route";
import * as route33 from "@/server/handlers/api/medicines/route";
import * as route34 from "@/server/handlers/api/notification-center/api-keys/route";
import * as route35 from "@/server/handlers/api/notification-center/channels/route";
import * as route36 from "@/server/handlers/api/notification-center/dispatch/route";
import * as route37 from "@/server/handlers/api/notification-center/groups/[id]/route";
import * as route38 from "@/server/handlers/api/notification-center/groups/[id]/routes/[channelId]/route";
import * as route39 from "@/server/handlers/api/notification-center/groups/route";
import * as route40 from "@/server/handlers/api/notification-center/templates/[id]/route";
import * as route41 from "@/server/handlers/api/notification-center/templates/route";
import * as route42 from "@/server/handlers/api/openapi.json/route";
import * as route43 from "@/server/handlers/api/push-ledger/route";
import * as route44 from "@/server/handlers/api/reminders/[id]/complete/route";
import * as route45 from "@/server/handlers/api/reminders/[id]/restore/route";
import * as route46 from "@/server/handlers/api/reminders/[id]/route";
import * as route47 from "@/server/handlers/api/reminders/route";
import * as route48 from "@/server/handlers/api/scheduler/status/route";
import * as route49 from "@/server/handlers/api/settings/bot/bindings/route";
import * as route50 from "@/server/handlers/api/settings/bot/route";
import * as route51 from "@/server/handlers/api/settings/otp/reset/route";
import * as route52 from "@/server/handlers/api/settings/r2/route";
import * as route53 from "@/server/handlers/api/settings/route";
import * as route54 from "@/server/handlers/api/settings/test-email/route";
import * as route55 from "@/server/handlers/api/ssl/route";
import * as route56 from "@/server/handlers/api/todos/[id]/route";
import * as route57 from "@/server/handlers/api/todos/route";
import * as route58 from "@/server/handlers/api/upload/route";
import * as route59 from "@/server/handlers/api/voice/transcriptions/route";
import * as route60 from "@/server/handlers/api/voice/tts/route";
import * as route61 from "@/server/handlers/cancel/[id]/route";
import * as route62 from "@/server/handlers/channels/route";
import * as route63 from "@/server/handlers/groups/route";
import * as route64 from "@/server/handlers/notifications/[id]/route";
import * as route65 from "@/server/handlers/notifications/route";
import * as route66 from "@/server/handlers/notify/route";
import * as route67 from "@/server/handlers/queue/jobs/route";
import * as route68 from "@/server/handlers/queue/retry/[job_id]/route";
import * as route69 from "@/server/handlers/templates/route";

import { compileRoute } from "./compile-route";
import type { RouteHandler } from "./types";

// Every registered module is checked by the manifest and contract tests. This adapter is
// the single boundary for route-specific parameter shapes such as { id } and { token }.
function adaptRouteHandler(handler: unknown): RouteHandler {
  return handler as RouteHandler;
}

export const routeRegistry = [
  { source: "app/.well-known/ai-plugin.json/route.ts", path: "/.well-known/ai-plugin.json", method: "GET" as const, handler: adaptRouteHandler(route0.GET) },
  { source: "app/api/admin/member-invitations/[id]/route.ts", path: "/api/admin/member-invitations/:id", method: "DELETE" as const, handler: adaptRouteHandler(route1.DELETE) },
  { source: "app/api/admin/members/[id]/revoke-access/route.ts", path: "/api/admin/members/:id/revoke-access", method: "POST" as const, handler: adaptRouteHandler(route2.POST) },
  { source: "app/api/admin/members/[id]/route.ts", path: "/api/admin/members/:id", method: "PATCH" as const, handler: adaptRouteHandler(route3.PATCH) },
  { source: "app/api/admin/members/route.ts", path: "/api/admin/members", method: "GET" as const, handler: adaptRouteHandler(route4.GET) },
  { source: "app/api/admin/members/route.ts", path: "/api/admin/members", method: "POST" as const, handler: adaptRouteHandler(route4.POST) },
  { source: "app/api/attachments/[id]/route.ts", path: "/api/attachments/:id", method: "DELETE" as const, handler: adaptRouteHandler(route5.DELETE) },
  { source: "app/api/attachments/route.ts", path: "/api/attachments", method: "GET" as const, handler: adaptRouteHandler(route6.GET) },
  { source: "app/api/auth/logout/route.ts", path: "/api/auth/logout", method: "POST" as const, handler: adaptRouteHandler(route7.POST) },
  { source: "app/api/auth/otp/login/route.ts", path: "/api/auth/otp/login", method: "POST" as const, handler: adaptRouteHandler(route8.POST) },
  { source: "app/api/auth/otp/setup/route.ts", path: "/api/auth/otp/setup", method: "POST" as const, handler: adaptRouteHandler(route9.POST) },
  { source: "app/api/auth/otp/verify-setup/route.ts", path: "/api/auth/otp/verify-setup", method: "POST" as const, handler: adaptRouteHandler(route10.POST) },
  { source: "app/api/auth/passkey/[id]/route.ts", path: "/api/auth/passkey/:id", method: "DELETE" as const, handler: adaptRouteHandler(route11.DELETE) },
  { source: "app/api/auth/passkey/list/route.ts", path: "/api/auth/passkey/list", method: "GET" as const, handler: adaptRouteHandler(route12.GET) },
  { source: "app/api/auth/passkey/login/route.ts", path: "/api/auth/passkey/login", method: "GET" as const, handler: adaptRouteHandler(route13.GET) },
  { source: "app/api/auth/passkey/login/verify/route.ts", path: "/api/auth/passkey/login/verify", method: "POST" as const, handler: adaptRouteHandler(route14.POST) },
  { source: "app/api/auth/passkey/register/route.ts", path: "/api/auth/passkey/register", method: "GET" as const, handler: adaptRouteHandler(route15.GET) },
  { source: "app/api/auth/passkey/register/verify/route.ts", path: "/api/auth/passkey/register/verify", method: "POST" as const, handler: adaptRouteHandler(route16.POST) },
  { source: "app/api/auth/status/route.ts", path: "/api/auth/status", method: "GET" as const, handler: adaptRouteHandler(route17.GET) },
  { source: "app/api/auth/trusted/devices/route.ts", path: "/api/auth/trusted/devices", method: "DELETE" as const, handler: adaptRouteHandler(route18.DELETE) },
  { source: "app/api/auth/trusted/devices/route.ts", path: "/api/auth/trusted/devices", method: "GET" as const, handler: adaptRouteHandler(route18.GET) },
  { source: "app/api/auth/trusted/restore/route.ts", path: "/api/auth/trusted/restore", method: "GET" as const, handler: adaptRouteHandler(route19.GET) },
  { source: "app/api/images/[id]/route.ts", path: "/api/images/:id", method: "DELETE" as const, handler: adaptRouteHandler(route20.DELETE) },
  { source: "app/api/images/route.ts", path: "/api/images", method: "GET" as const, handler: adaptRouteHandler(route21.GET) },
  { source: "app/api/images/route.ts", path: "/api/images", method: "POST" as const, handler: adaptRouteHandler(route21.POST) },
  { source: "app/api/invite/[token]/passkey/options/route.ts", path: "/api/invite/:token/passkey/options", method: "POST" as const, handler: adaptRouteHandler(route22.POST) },
  { source: "app/api/invite/[token]/passkey/verify/route.ts", path: "/api/invite/:token/passkey/verify", method: "POST" as const, handler: adaptRouteHandler(route23.POST) },
  { source: "app/api/invite/[token]/totp/setup/route.ts", path: "/api/invite/:token/totp/setup", method: "POST" as const, handler: adaptRouteHandler(route24.POST) },
  { source: "app/api/invite/[token]/totp/verify/route.ts", path: "/api/invite/:token/totp/verify", method: "POST" as const, handler: adaptRouteHandler(route25.POST) },
  { source: "app/api/license/generate/route.ts", path: "/api/license/generate", method: "POST" as const, handler: adaptRouteHandler(route26.POST) },
  { source: "app/api/license/store-accounts/[id]/payment-qr/route.ts", path: "/api/license/store-accounts/:id/payment-qr", method: "DELETE" as const, handler: adaptRouteHandler(route27.DELETE) },
  { source: "app/api/license/store-accounts/[id]/payment-qr/route.ts", path: "/api/license/store-accounts/:id/payment-qr", method: "GET" as const, handler: adaptRouteHandler(route27.GET) },
  { source: "app/api/license/store-accounts/[id]/payment-qr/route.ts", path: "/api/license/store-accounts/:id/payment-qr", method: "POST" as const, handler: adaptRouteHandler(route27.POST) },
  { source: "app/api/license/store-accounts/[id]/route.ts", path: "/api/license/store-accounts/:id", method: "DELETE" as const, handler: adaptRouteHandler(route28.DELETE) },
  { source: "app/api/license/store-accounts/[id]/route.ts", path: "/api/license/store-accounts/:id", method: "PUT" as const, handler: adaptRouteHandler(route28.PUT) },
  { source: "app/api/license/store-accounts/route.ts", path: "/api/license/store-accounts", method: "GET" as const, handler: adaptRouteHandler(route29.GET) },
  { source: "app/api/license/store-accounts/route.ts", path: "/api/license/store-accounts", method: "POST" as const, handler: adaptRouteHandler(route29.POST) },
  { source: "app/api/mcp/route.ts", path: "/api/mcp", method: "DELETE" as const, handler: adaptRouteHandler(route30.DELETE) },
  { source: "app/api/mcp/route.ts", path: "/api/mcp", method: "GET" as const, handler: adaptRouteHandler(route30.GET) },
  { source: "app/api/mcp/route.ts", path: "/api/mcp", method: "OPTIONS" as const, handler: adaptRouteHandler(route30.OPTIONS) },
  { source: "app/api/mcp/route.ts", path: "/api/mcp", method: "POST" as const, handler: adaptRouteHandler(route30.POST) },
  { source: "app/api/medicines/[id]/attachments/route.ts", path: "/api/medicines/:id/attachments", method: "GET" as const, handler: adaptRouteHandler(route31.GET) },
  { source: "app/api/medicines/[id]/attachments/route.ts", path: "/api/medicines/:id/attachments", method: "POST" as const, handler: adaptRouteHandler(route31.POST) },
  { source: "app/api/medicines/[id]/route.ts", path: "/api/medicines/:id", method: "DELETE" as const, handler: adaptRouteHandler(route32.DELETE) },
  { source: "app/api/medicines/[id]/route.ts", path: "/api/medicines/:id", method: "GET" as const, handler: adaptRouteHandler(route32.GET) },
  { source: "app/api/medicines/[id]/route.ts", path: "/api/medicines/:id", method: "PUT" as const, handler: adaptRouteHandler(route32.PUT) },
  { source: "app/api/medicines/route.ts", path: "/api/medicines", method: "GET" as const, handler: adaptRouteHandler(route33.GET) },
  { source: "app/api/medicines/route.ts", path: "/api/medicines", method: "POST" as const, handler: adaptRouteHandler(route33.POST) },
  { source: "app/api/notification-center/api-keys/route.ts", path: "/api/notification-center/api-keys", method: "GET" as const, handler: adaptRouteHandler(route34.GET) },
  { source: "app/api/notification-center/api-keys/route.ts", path: "/api/notification-center/api-keys", method: "POST" as const, handler: adaptRouteHandler(route34.POST) },
  { source: "app/api/notification-center/channels/route.ts", path: "/api/notification-center/channels", method: "GET" as const, handler: adaptRouteHandler(route35.GET) },
  { source: "app/api/notification-center/channels/route.ts", path: "/api/notification-center/channels", method: "POST" as const, handler: adaptRouteHandler(route35.POST) },
  { source: "app/api/notification-center/dispatch/route.ts", path: "/api/notification-center/dispatch", method: "POST" as const, handler: adaptRouteHandler(route36.POST) },
  { source: "app/api/notification-center/groups/[id]/route.ts", path: "/api/notification-center/groups/:id", method: "PATCH" as const, handler: adaptRouteHandler(route37.PATCH) },
  { source: "app/api/notification-center/groups/[id]/routes/[channelId]/route.ts", path: "/api/notification-center/groups/:id/routes/:channelId", method: "DELETE" as const, handler: adaptRouteHandler(route38.DELETE) },
  { source: "app/api/notification-center/groups/[id]/routes/[channelId]/route.ts", path: "/api/notification-center/groups/:id/routes/:channelId", method: "PUT" as const, handler: adaptRouteHandler(route38.PUT) },
  { source: "app/api/notification-center/groups/route.ts", path: "/api/notification-center/groups", method: "GET" as const, handler: adaptRouteHandler(route39.GET) },
  { source: "app/api/notification-center/groups/route.ts", path: "/api/notification-center/groups", method: "POST" as const, handler: adaptRouteHandler(route39.POST) },
  { source: "app/api/notification-center/templates/[id]/route.ts", path: "/api/notification-center/templates/:id", method: "PATCH" as const, handler: adaptRouteHandler(route40.PATCH) },
  { source: "app/api/notification-center/templates/route.ts", path: "/api/notification-center/templates", method: "GET" as const, handler: adaptRouteHandler(route41.GET) },
  { source: "app/api/notification-center/templates/route.ts", path: "/api/notification-center/templates", method: "POST" as const, handler: adaptRouteHandler(route41.POST) },
  { source: "app/api/openapi.json/route.ts", path: "/api/openapi.json", method: "GET" as const, handler: adaptRouteHandler(route42.GET) },
  { source: "app/api/push-ledger/route.ts", path: "/api/push-ledger", method: "GET" as const, handler: adaptRouteHandler(route43.GET) },
  { source: "app/api/reminders/[id]/complete/route.ts", path: "/api/reminders/:id/complete", method: "POST" as const, handler: adaptRouteHandler(route44.POST) },
  { source: "app/api/reminders/[id]/restore/route.ts", path: "/api/reminders/:id/restore", method: "POST" as const, handler: adaptRouteHandler(route45.POST) },
  { source: "app/api/reminders/[id]/route.ts", path: "/api/reminders/:id", method: "DELETE" as const, handler: adaptRouteHandler(route46.DELETE) },
  { source: "app/api/reminders/[id]/route.ts", path: "/api/reminders/:id", method: "GET" as const, handler: adaptRouteHandler(route46.GET) },
  { source: "app/api/reminders/[id]/route.ts", path: "/api/reminders/:id", method: "PUT" as const, handler: adaptRouteHandler(route46.PUT) },
  { source: "app/api/reminders/route.ts", path: "/api/reminders", method: "GET" as const, handler: adaptRouteHandler(route47.GET) },
  { source: "app/api/reminders/route.ts", path: "/api/reminders", method: "POST" as const, handler: adaptRouteHandler(route47.POST) },
  { source: "app/api/scheduler/status/route.ts", path: "/api/scheduler/status", method: "GET" as const, handler: adaptRouteHandler(route48.GET) },
  { source: "app/api/settings/bot/bindings/route.ts", path: "/api/settings/bot/bindings", method: "GET" as const, handler: adaptRouteHandler(route49.GET) },
  { source: "app/api/settings/bot/bindings/route.ts", path: "/api/settings/bot/bindings", method: "POST" as const, handler: adaptRouteHandler(route49.POST) },
  { source: "app/api/settings/bot/route.ts", path: "/api/settings/bot", method: "GET" as const, handler: adaptRouteHandler(route50.GET) },
  { source: "app/api/settings/bot/route.ts", path: "/api/settings/bot", method: "POST" as const, handler: adaptRouteHandler(route50.POST) },
  { source: "app/api/settings/bot/route.ts", path: "/api/settings/bot", method: "PUT" as const, handler: adaptRouteHandler(route50.PUT) },
  { source: "app/api/settings/otp/reset/route.ts", path: "/api/settings/otp/reset", method: "POST" as const, handler: adaptRouteHandler(route51.POST) },
  { source: "app/api/settings/r2/route.ts", path: "/api/settings/r2", method: "GET" as const, handler: adaptRouteHandler(route52.GET) },
  { source: "app/api/settings/r2/route.ts", path: "/api/settings/r2", method: "POST" as const, handler: adaptRouteHandler(route52.POST) },
  { source: "app/api/settings/r2/route.ts", path: "/api/settings/r2", method: "PUT" as const, handler: adaptRouteHandler(route52.PUT) },
  { source: "app/api/settings/route.ts", path: "/api/settings", method: "GET" as const, handler: adaptRouteHandler(route53.GET) },
  { source: "app/api/settings/route.ts", path: "/api/settings", method: "PUT" as const, handler: adaptRouteHandler(route53.PUT) },
  { source: "app/api/settings/test-email/route.ts", path: "/api/settings/test-email", method: "POST" as const, handler: adaptRouteHandler(route54.POST) },
  { source: "app/api/ssl/route.ts", path: "/api/ssl", method: "GET" as const, handler: adaptRouteHandler(route55.GET) },
  { source: "app/api/ssl/route.ts", path: "/api/ssl", method: "POST" as const, handler: adaptRouteHandler(route55.POST) },
  { source: "app/api/todos/[id]/route.ts", path: "/api/todos/:id", method: "DELETE" as const, handler: adaptRouteHandler(route56.DELETE) },
  { source: "app/api/todos/[id]/route.ts", path: "/api/todos/:id", method: "PATCH" as const, handler: adaptRouteHandler(route56.PATCH) },
  { source: "app/api/todos/route.ts", path: "/api/todos", method: "GET" as const, handler: adaptRouteHandler(route57.GET) },
  { source: "app/api/todos/route.ts", path: "/api/todos", method: "POST" as const, handler: adaptRouteHandler(route57.POST) },
  { source: "app/api/upload/route.ts", path: "/api/upload", method: "GET" as const, handler: adaptRouteHandler(route58.GET) },
  { source: "app/api/upload/route.ts", path: "/api/upload", method: "POST" as const, handler: adaptRouteHandler(route58.POST) },
  { source: "app/api/voice/transcriptions/route.ts", path: "/api/voice/transcriptions", method: "POST" as const, handler: adaptRouteHandler(route59.POST) },
  { source: "app/api/voice/tts/route.ts", path: "/api/voice/tts", method: "POST" as const, handler: adaptRouteHandler(route60.POST) },
  { source: "app/cancel/[id]/route.ts", path: "/cancel/:id", method: "POST" as const, handler: adaptRouteHandler(route61.POST) },
  { source: "app/channels/route.ts", path: "/channels", method: "GET" as const, handler: adaptRouteHandler(route62.GET) },
  { source: "app/channels/route.ts", path: "/channels", method: "POST" as const, handler: adaptRouteHandler(route62.POST) },
  { source: "app/groups/route.ts", path: "/groups", method: "GET" as const, handler: adaptRouteHandler(route63.GET) },
  { source: "app/groups/route.ts", path: "/groups", method: "POST" as const, handler: adaptRouteHandler(route63.POST) },
  { source: "app/notifications/[id]/route.ts", path: "/notifications/:id", method: "GET" as const, handler: adaptRouteHandler(route64.GET) },
  { source: "app/notifications/route.ts", path: "/notifications", method: "GET" as const, handler: adaptRouteHandler(route65.GET) },
  { source: "app/notify/route.ts", path: "/notify", method: "POST" as const, handler: adaptRouteHandler(route66.POST) },
  { source: "app/queue/jobs/route.ts", path: "/queue/jobs", method: "GET" as const, handler: adaptRouteHandler(route67.GET) },
  { source: "app/queue/retry/[job_id]/route.ts", path: "/queue/retry/:job_id", method: "POST" as const, handler: adaptRouteHandler(route68.POST) },
  { source: "app/templates/route.ts", path: "/templates", method: "GET" as const, handler: adaptRouteHandler(route69.GET) },
  { source: "app/templates/route.ts", path: "/templates", method: "POST" as const, handler: adaptRouteHandler(route69.POST) },
].map(compileRoute);
